spring:
  sql.init.mode: never
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL}
    externalUrl: ${DATABASE_EXTERNAL_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}